### ISSUE TITLE
need standalone restore routine

### ISSUE THREAD

**Issue by ptube** [rwese/DockWin#4]
Hi guys!
I'm a autohotkey newbie. I tried some hours to separate the Restore subroutine in a standalone routine for starting automatically after Windows logon. But I havent luck with my work.
Plz help me

ptube

**Comment by rwese** [comment]
@ptube your goal is to have it restore the saved configuration on load?

**Comment by ptube** [comment]
yes, so I have my program windows on the right position at start

**Comment by rwese** [comment]
I made a change for this, you can now use /restore to have it restore the positions on start.
Works best if you compile it to an exe first.

**Comment by ptube** [comment]
Great! thx a lot
