### ISSUE TITLE
Minimized windows not recorded

### ISSUE THREAD

**Issue by teknowledgist** [rwese/DockWin#5]
In short, this script isn't capturing/recording when windows are minimized, but not having much experience with AHK, I don't know how to fix it.

When I "capture screens" on my Win7x64 system with AHK 1.1.23.05, the windows all cycle through (which, I guess, I would expect), but all the minimized windows open and don't re-minimize (although the ashleydawson post claims it does).  

When I look at the `WinPos.txt` file, there are no `maximized=-1` items.  As I would expect, when I "restore screens", all the windows open including those that had been minimized during the capture.

If I manually edit the `WinPos.txt` file to set some `maximized=-1` items (from `maximized=0` that they are all set to), the restore does end with them minimized.  (They do open, but then minimize.)

**Comment by rwese** [comment]
Will look into it.

The expected behavior is to have the windows minimized if they are opened?

**Comment by rwese** [comment]
Seems like a bug in AHK

```
    WinGet, win_maximized, minmax, %this_title%
```

Will only return 0/1

**Comment by rwese** [comment]
Switching to use class works

```
    this_id := id%A_Index%
    WinGetClass, this_class, ahk_id %this_id%
    WinGetTitle, this_title, ahk_id %this_id%
    WinGet, win_maximized, minmax, ahk_class %this_class%
    WinActivate, ahk_id %this_id%
    WinGetPos, x, y, Width, Height, A ;Wintitle
```

Restoring is buggy

**Comment by rwese** [comment]
@teknowledgist should work now, the restoring was working fine, i just had a wrong test.
Let me know if any further issues arise.

**Comment by teknowledgist** [comment]
@René Thanks!  FYI, you have v0.7 in the header and v0.6 as the title.

**Comment by rwese** [comment]
thanks, fixed! :)
